//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompPlanLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GVLMSS01;Initial Catalog=awireless_development;Persist Security Info=" +
            "True;User ID=wrap_user;Password=$$rq41234")]
        public string awireless_developmentConnectionString {
            get {
                return ((string)(this["awireless_developmentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=repservice01.iqmetrix.net;Initial Catalog=AWireless;Persist Security " +
            "Info=True;User ID=AWirelessUser;Password=2awi439$;ApplicationIntent=ReadOnly")]
        public string AWirelessConnectionString {
            get {
                return ((string)(this["AWirelessConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gvlmss01;Initial Catalog=rq4_local;Persist Security Info=True;User ID" +
            "=wrap_user;Password=$$rq41234;ApplicationIntent=ReadOnly")]
        public string rq4_localConnectionString {
            get {
                return ((string)(this["rq4_localConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GVLMSS01;Initial Catalog=awireless_development;Persist Security Info=" +
            "True;User ID=wrap_user;Password=$$rq41234")]
        public string awireless_developmentConnectionString1 {
            get {
                return ((string)(this["awireless_developmentConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GVLMSS01;Initial Catalog=awireless_development;Integrated Security=Tr" +
            "ue")]
        public string awireless_developmentConnectionString2 {
            get {
                return ((string)(this["awireless_developmentConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GVLSQL01;Initial Catalog=compplan_testing;Integrated Security=True")]
        public string compplan_testingConnectionString {
            get {
                return ((string)(this["compplan_testingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GVLMSS04;Initial Catalog=awireless_development;Integrated Security=Tr" +
            "ue")]
        public string awireless_developmentConnectionString3 {
            get {
                return ((string)(this["awireless_developmentConnectionString3"]));
            }
        }
    }
}
